import type { Metadata } from 'next';
import { Inter, Inter_Tight, Mona_Sans, Outfit, Rethink_Sans, Roboto } from 'next/font/google';
import { ViewfinderProvider } from '@/viewfinder-context';
import { CursorProvider } from '@/cursor-context';
import { Cursor, Drawer } from '@/components';
import { DrawerProvider } from '@/drawer-context';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });
const interTight = Inter_Tight({ subsets: ['latin'] });
const outfit = Outfit({ subsets: ['latin'] });
const rethink = Rethink_Sans({ subsets: ['latin'] });
const roboto = Roboto({ subsets: ['latin'] });
const mona = Mona_Sans({ subsets: ['latin'] });
const classname = [
  inter.className,
  interTight.className,
  outfit.className,
  rethink.className,
  roboto.className,
  mona.className,
].join(' ');

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <CursorProvider>
        <body className={classname}>
          <ViewfinderProvider>
            <DrawerProvider>
              {children}
              <Drawer />
              <Cursor />
            </DrawerProvider>
          </ViewfinderProvider>
        </body>
      </CursorProvider>
    </html>
  );
}
