import type { Metadata } from 'next';
import { ViewfinderProvider } from '@/viewfinder-context';
import { CursorProvider } from '@/cursor-context';
import { Cursor } from '@/components';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CursorProvider>
        <body>
          <ViewfinderProvider>
            {children}
            <Cursor />
          </ViewfinderProvider>
        </body>
      </CursorProvider>
    </html>
  );
}
